name: Nightly Compound Review

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  compound:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for git log history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Universal Compounder
        run: pip install git+https://github.com/your-username/universal-compounder.git

      - name: Run Compound Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: compound run --provider openai

      - name: Commit Report
        run: |
          git config --global user.name "Compound Bot"
          git config --global user.email "bot@example.com"
          git add docs/knowledge/
          git commit -m "docs: add nightly compound report" || echo "No changes to commit"
          git push
